### ISSUE TITLE
Indicação visual de que o request está sendo processado

### ISSUE THREAD

**Issue by andrechalom** [merepresenta/merepresenta#15]
O request está demorando alguns segundos para ser processado, e não há nenhuma indicação visual de que ele está esperando uma resposta. Isso faz com que o usuário fique impaciente, clique novamente no botão de "filtro", sobrecarregando ainda mais o servidor. Sugiro incluir um spinner, como um elemento div com o seguinte css:

```css
#spinner {
 border-top: 3px solid <cor escolhida>;
 border-bottom: 3px solid <cor escolhida>;
  border-radius: 50%;
    width: 20px;
    height: 20px;
    animation: spin 2s ease-in-out infinite;
    display: none;
}

@keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
}
```

O request mostra o spinner, e a chamada de "$.ajax({ ... success:" muda o elemento novamente pra "display: none";
